### ISSUE TITLE
[Security] Use yaml.SafeLoader instead of yaml.Loader/yaml.FullLoader (same as yaml.UnsafeLoader)

### ISSUE THREAD

**Issue by kamadorueda** [awslabs/aws-cfn-template-flip#101]
here: https://github.com/awslabs/aws-cfn-template-flip/blob/master/cfn_tools/yaml_loader.py#L20

![image](https://user-images.githubusercontent.com/47480384/92981752-da9d4880-f460-11ea-84cf-3df982f8fc29.png)

as explained here:

https://pyyaml.org/wiki/PyYAMLDocumentation#LoadingYAML

![image](https://user-images.githubusercontent.com/47480384/92981765-ebe65500-f460-11ea-98c4-fb68f2c563da.png)

an in the source-code comment:

![image](https://user-images.githubusercontent.com/47480384/92981779-fd2f6180-f460-11ea-9581-f8d6e5eb11bd.png)

is insecure, we should use SafeLoader instead

**Comment by koiker** [comment]
I have updated the Loader to FullLoader in the fix/max-col-width. Are you using Python 2.7 or 3.x?
The new version will deprecate python 2.7 and will only work with python 3.x

**Comment by kamadorueda** [comment]
That's awesome!

**Comment by kamadorueda** [comment]
Seems like FullLoader is also vulnerable: https://github.com/yaml/pyyaml/issues/420

I've updated the issue

**Comment by koiker** [comment]
Fixed in #102
