### ISSUE TITLE
Command line version doesn't seem to work with Bash Ubuntu on windows

### ISSUE THREAD

**Issue by mungojam** [awslabs/aws-cfn-template-flip#11]
I run the pip install command, which runs without error, but cfn-flip is not found when I try running it. Maybe it's installed somewhere that isn't on the default path or something:

mark@MyComp:/$ pip install cfn_flip
Requirement already satisfied: cfn_flip in /home/mark/.local/lib/python2.7/site-packages
Requirement already satisfied: PyYAML in /home/mark/.local/lib/python2.7/site-packages (from cfn_flip)
Requirement already satisfied: six in /home/mark/.local/lib/python2.7/site-packages (from cfn_flip)

mark@MyComp:/$ cfn-flip
cfn-flip: command not found

mark@MyComp:/$ locate cfn-flip

mark@MyComp:/$

**Comment by GMartinez-Sisti** [comment]
Hi @mungojam,

I just tried it in a fresh install of Bash on Windows and it worked perfecty.

All I did was:
```
sudo apt-get install python-pip
pip install cfn_flip
```

It was installed here:
```
user@folder$ whereis cfn-flip
cfn-flip: /usr/local/bin/cfn-flip
```

I already converted a template successfully. 

Hope it helps.

Regards

**Comment by mungojam** [comment]
Thanks for trying it out. You've led me to the source of the issue, which may be an issue with pip or bash on windows. 

Above you are using sudo for the pip command, which isn't what the readme shows so I didn't use it. (Though I understand it's different for different OSes). 

Uninstalling has shown me where the bin has ended up in my case (not sure why whereis doesn't find it, perhaps because it's in a hidden folder):

```
pip uninstall cfn_flip
Uninstalling cfn-flip-0.2.1:
  /home/mark/.local/bin/cfn-flip
 /home/mark/.local/lib/python2.7/site-packages/cfn_flip-0.2.1.dist-info/DESCRIPTION.rst
...
```

After uninstalling and reinstalling as sudo, I was able to get it to work, though I get a warning, which looks like a pip bug to me:

```
sudo pip install cfn_flip
[sudo] password for mark:
The directory '/home/mark/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/mark/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: cfn_flip in /home/mark/.local/lib/python2.7/site-packages
Requirement already satisfied: PyYAML in /home/mark/.local/lib/python2.7/site-packages (from cfn_flip)
Requirement already satisfied: six in /home/mark/.local/lib/python2.7/site-packages (from cfn_flip)

```

**Comment by mungojam** [comment]
I've raised [an issue](https://github.com/Microsoft/BashOnWindows/issues/2148) against BashOnWindows since it seems it is a fairly standard path for ubuntu that isn't being included.

Happy to close this, thanks for your help in diagnosing
