### ISSUE TITLE
Empty assignment line in json join leads to poor 'clean' result

### ISSUE THREAD

**Issue by mungojam** [awslabs/aws-cfn-template-flip#12]
When a line in the json Join ends in a space e.g. `x = `, this leads the result of -c to leave in line breaks. In the working example below, the yaml has the lines split apart as desired, but in the failing example, it does not:

Working example
```
{
  "content": { "Fn::Join": [ "", [
    "line1 = g\n",
    "line2 = h\n"
  ] ] }
}
```
correctly becomes:
```
content: 'line1 = g

  line2 = h

  '
```
Failing example:
```
{
  "content": { "Fn::Join": [ "", [
    "line1 = g\n",
    "line2 = \n"
  ] ] }
}
```
becomes
```
content: "line1 = g\nline2 = \n"
```
The example here is from one an Amazon blog post [here](https://aws.amazon.com/blogs/devops/view-cloudformation-logs-in-the-console/)

**Comment by stilvoid** [comment]
This is fixed in 451d01fec6970e20c93a22e206072ac0788f0111. New pip release coming soon.
