### ISSUE TITLE
Escaped newlines in json result in de-escaped newlines in yml

### ISSUE THREAD

**Issue by charltones** [awslabs/aws-cfn-template-flip#13]
For example:

` >>> a='[1, 2, "hello\\n\\n"]'`
` >>> print cfn_flip.flip(a)`
` - 1`
` - 2`
` - 'hello`
` `
` `
` '`

I guess these should either remain escaped within double quotes or be turned into literals. This is a common pattern for joining large blocks of text as e.g. an embedded script.

**Comment by stilvoid** [comment]
Fixed in 451d01fec6970e20c93a22e206072ac0788f0111. New pip release coming soon.
