### ISSUE TITLE
What is the type of "some_json_or_yaml" ?

### ISSUE THREAD

**Issue by emayssat-ms** [awslabs/aws-cfn-template-flip#2]
In the docs it  says:
[...]
from cfn_flip import flip, to_yaml, to_json

some_yaml_or_json = flip(some_json_or_yaml)
some_json = to_json(some_yaml)
some_yaml = to_yaml(some_json)
clean_yaml = to_yaml(some_json, clean_up=True)
[...]
What is some_json_or_yaml? Is it a file, a python representation of json/yaml, a string, or other?

**Comment by stilvoid** [comment]
Thanks for the comment. I've updated the readme to clarify, hopefully that helps :)
