### ISSUE TITLE
Add possibility to convert to YAML full function name

### ISSUE THREAD

**Issue by sanyer** [awslabs/aws-cfn-template-flip#25]
Would be useful when using `AWS::Include Transform` as AWS docs says: _We do not currently support using shorthand notations for YAML snippets._

**Comment by stilvoid** [comment]
Good idea. I'll get this on the backlog :)

**Comment by stilvoid** [comment]
Added in b2ab4ff542841f61df4b6e1cb186facd0ce83011

**Comment by sanyer** [comment]
awesome! 👍
