### ISSUE TITLE
!Sub created by clean doesn't escape literal ${VAR}

### ISSUE THREAD

**Issue by azatoth** [awslabs/aws-cfn-template-flip#28]
For example in a UserData for a EC2, you might have a bash script and thus can have items like `${VAR}` literally in the text. These should be escaped to `${!VAR}`per http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html#w2ab2c21c28c56b7

**Comment by stilvoid** [comment]
Fixed in c124d31db0c1190f4fcd1fadb71e46945cd2bff8. New pip version coming soon.
