### ISSUE TITLE
Use real short form for !GetAtt

### ISSUE THREAD

**Issue by sanyer** [awslabs/aws-cfn-template-flip#3]
Instead of 

```yaml
!GetAtt [ logicalNameOfResource, attributeName ]
```

there should be 

```yaml
!GetAtt logicalNameOfResource.attributeName
```

**Comment by stilvoid** [comment]
Thanks for raising this. I actually already have this working in a branch with a bunch of other validation work that uses the CloudFormation specification file. I hope to push it up for visibility soon.

**Comment by sanyer** [comment]
Awesome :-)
Already have a place to track new features :-)
