### ISSUE TITLE
cfn-flip with `--clean` flag throws `'dict' object attribute 'items' is read-only` error

### ISSUE THREAD

**Issue by dougireton** [awslabs/aws-cfn-template-flip#4]
# Summary
cfn-flip 0.2.0

`cfn-flip` with `--clean` option throws error on AWS template for JIRA.

## Repro Steps

1. Download this [AWS Quickstart template for JIRA](https://s3.amazonaws.com/quickstart-reference/atlassian/jira/latest/templates/JiraDataCenter.template).
2. Run `cfn-flip -c JiraDataCenter.template`

If you run it without `--clean`, it flips the JSON to YAML without errors.

## Results:
Error: `'dict' object attribute 'items' is read-only`

**Comment by stilvoid** [comment]
Yep. This was stupid code that was never tested or working ;) dict is (usually) a CPython implementation and can't be abused like that. Fixed by subclassing it.
