### ISSUE TITLE
Error: 'int' object has no attribute 'replace'

### ISSUE THREAD

**Issue by reidca** [awslabs/aws-cfn-template-flip#44]
Trying to convert a json template into yaml results in the error Error: 'int' object has no attribute 'replace'

Converting the same template in the cloud formation designer in the AWS console results in a properly formatted YAML file.

Taking this formatted YAML file and doing a --clean --no-flip results in a file with the value "null
..."

The template in question is an AWS supplied template which can be obtained from here:
https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/instance-scheduler.template

It is referenced in the following document:
https://docs.aws.amazon.com/solutions/latest/instance-scheduler/deployment.html

**Comment by stilvoid** [comment]
Nice catch. This is actually down to a dubious use of `Fn::Join` in the template so I'll see if I can get that template changed.

The [Fn::Join docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-join.html) say that the second parameter should be a list. In this template (line 748) a Ref object is used directly without wrapping it in a list. In fact, the Join is pointless there as it contains only one item.

I'm adding a fix to cfn-flip that will handle this case regardless and should get it committed later today.

**Comment by stilvoid** [comment]
I take that comment back - that's a legitimate use of Join as the Ref resolves to a list of course :)

Fix coming soon either way.

**Comment by stilvoid** [comment]
Fixed in 1.0.3
