### ISSUE TITLE
Combining cfn-flip with cfn-lint when cleaning code

### ISSUE THREAD

**Issue by reidca** [awslabs/aws-cfn-template-flip#48]
There are a few cases where cleaning the code does not agree with warnings that cfn-lint exposes.

An example is the Security Group ingress 'FromPort' and 'ToPort' properties which should be integers but cfn-flip either makes no judgement on this or converts them to strings.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule.html

Also, cfn-flip puts the parameter for intrinsic functions such as Condition, Ref and GetAtt as strings whereas cfn-lint makes no judgement on this and according to the spec they do not need to be strings.

e.g. PrivateIp:
    Description: PrivateIp of the newly created EC2 instance
    Value: !GetAtt EC2Instance.PrivateIp

Becomes 

PrivateIp:
    Description: PrivateIp of the newly created EC2 instance
    Value: !GetAtt 'EC2Instance.PrivateIp'

After going through a cfn-flip clean. I cannot see why the parameter needs to be wrapped in quotes as it works perfectly well without them and in my opinion better represents what it is which is an object with a property.

Ideally cfn-flip would use the linting rules that cfn-lint has when it is doing it's cleaning.

**Comment by stilvoid** [comment]
Hi. Given that cfn-lint is considerably more comprehensive than cfn-flip with regard to applying the CloudFormation spec, I think it's likely that I'll drop the `clean` functionality from cfn-flip in a future release.

With that in mind, this is going down as a "won't fix" for now.

**Comment by reidca** [comment]
cfn-lint is a great tool but it does not offer the same functionality as the "clean" command in cfn-flip.
I use the clean command to achieve a consistent format in my templates and make use of Sub instead of join etc. cfn-link makes suggestions but as far as I am aware you cannot ask it to make opinionated formatting of your code - perhaps this i something they could add but I would hate to see cfn-flip lose this functionality without an alternative.

**Comment by stilvoid** [comment]
So I did a considerable amount of digging into the darkest depths of pyyaml and I can't find a good way to get it to force tagged string (e.g. `!GetAtt foo.bar`) to serialise without quotes :(

I'm going to close this for now but I'll likely investigate another, more flexible yaml library to use for cfn-flip in future which might also solve this issue.
