### ISSUE TITLE
pip install may fail because of the setup_requires dependency for those who have pip configurations

### ISSUE THREAD

**Issue by vishnya** [awslabs/aws-cfn-template-flip#49]
`pip install` fails because distutils tries to do the install and ignores any pip configurations that have be set. For those of us who have pip configurations set, this might cause a SSL error like this:

```distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/72/a4/d7a5738a3096f22a98bec1609e237b250ebff04e5ea2930305d485337263/pytest_runner-4.2-py2.py3-none-any.whl#sha256=d987fec1e31287592ffe1cb823a8c613c533db4c6aaca0ee1191dbc91e2fcc61: EOF occurred in violation of protocol (_ssl.c:833)``` 

It would be better to at least have a try/except statement around the dependencies with the appropriate error raised to install them.

**Comment by stilvoid** [comment]
Closing for now.
