### ISSUE TITLE
Pinned dependency versions causes incompatibilities

### ISSUE THREAD

**Issue by mithun** [awslabs/aws-cfn-template-flip#56]
v1.0.5 has dependencies pinned to absolute versions. This causes conflicts and `pip check` errors when `cfn-flip` is being installed as a development utility alongside other dependencies.

Can 7ccbf102d96c6f2a6bd4a16650415a765b7564ee be reverted to use compatible version ranges instead of absolute versions?

**Comment by phobologic** [comment]
We are running into this as well in https://github.com/cloudtools/stacker - curious why it was pinned in the first place?

**Comment by stilvoid** [comment]
Oops yes, you're right. Over-zealous noob error. I'll fix this today.

**Comment by stilvoid** [comment]
Fixed in #58. Released to pypi as 1.0.6.

**Comment by phobologic** [comment]
Thanks so much @stilvoid !
