### ISSUE TITLE
Syntax error messages could be improved

### ISSUE THREAD

**Issue by carlnordenfelt** [awslabs/aws-cfn-template-flip#57]
Error messages could be improved to make trouble shooting easier:

    cfn-flip ./template.yaml 
    Error: Could not determine the input format

Turned out ot be due to lingering commas in the yaml file.
Running the same template through https://www.json2yaml.com/ correctly identified the source of the error::

    Did Not Find Expected Key While Parsing A Block Mapping At Line 83 Column 13`

Once the offending comma was removed, cfn-flip worked perfectly. I wouldn't have found that issue just using cfn-flip however.

**Comment by stilvoid** [comment]
Fixed in #59
