### ISSUE TITLE
Setuptools fails to install 1.1.0.post1 (utf8 character in README.md decoded as ASCII)

### ISSUE THREAD

**Issue by gustafj** [awslabs/aws-cfn-template-flip#61]
Setuptools fails to install the latest release (1.1.0.post1), it fails to decode a (utf8 encoded) character using the default `ascii` codec.

The problem is the `’` (U+2019) in `format’s` on line 8 of the `README.md`, which is encoded as `0xE2 0x80 0x99`:
https://github.com/awslabs/aws-cfn-template-flip/blob/22d266c3aa268c0515d6c72f9f474f3fd3cef737/README.md#L8

This stems from the read of `README.md` performed in `setup.py`: 
https://github.com/awslabs/aws-cfn-template-flip/blob/22d266c3aa268c0515d6c72f9f474f3fd3cef737/setup.py#L17

Stacktrace:
```
Running cfn_flip-1.1.0.post1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-sceqptzl/cfn_flip-1.1.0.post1/egg-dist-tmp-tuve9xpi
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
     yield saved
   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
     yield
   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
     DirectorySandbox(setup_dir).run(runner)
   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
     return func()
   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
     _execfile(setup_script, ns)
   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
     exec(code, globals, locals)
   File "/tmp/easy_install-sceqptzl/cfn_flip-1.1.0.post1/setup.py", line 17, in <module>
   File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
     return codecs.ascii_decode(input, self.errors)[0]
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 516: ordinal not in range(128)
```

**Comment by koiker** [comment]
I'm trying to reproduce the issue using the py35 env in tox but it's passing.
I think this could be something related with your local operational system environment.
Can you show your current environment variables? I'm thinking this could be something related with your locale

**Comment by gustafj** [comment]
This was being executed within a docker container that is based on `microsoft/vsts-agent:ubuntu-16.04`.
And that does not set neither `LANG`, nor `LC_ALL`.
Running `cfn_flip` directly gives me this:
```
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
```
So I think you are right that this is indeed a env issue, however it still seems quite bad to crash if the users env is set to use ASCII.

**Comment by stilvoid** [comment]
It seems this is a long-standing issue with Click and so we can't successfully address it within cfn-flip. That said, I did fix the apostrophe in the README as it annoyed me once you'd pointed it out :)
