### ISSUE TITLE
setup.py is using setup_requires which is causing issues with pip in certain environments

### ISSUE THREAD

**Issue by mervynrussell** [awslabs/aws-cfn-template-flip#76]
We use pip to install packages for our build pipelines and for vendoring packages prior to deployment onto our cloud environment.  The use of setup_requires bypasses the pip installation and means we have to hack around with our pipelines in order to fix these up.  Is the dependency on pytest-runner for setup of cfn-flip actually required and if not can it be removed?  pip user guide actively discourages use of setup_requires.

**Comment by koiker** [comment]
It's interesting that `pytest-runner` has this statement to use setup_requires in their documentation:

https://pypi.org/project/pytest-runner/

And the latest version 5.0 launched this year still states to use this technique.

I will test moving this dependency that is just used to build the package to `test_require`

**Comment by mervynrussell** [comment]
Thanks Rafael.  Yeah, I saw that in their docs too when we first started using cfn-flip and encountered the problem. Note pytest-runner document does outline how to add it to ```setup_requires``` conditionally if you find that ```test_require``` doesn't work for you.

**Comment by stilvoid** [comment]
Fixed in #77 :)

**Comment by mervynrussell** [comment]
Thanks guys!
