### ISSUE TITLE
Use AWS compress yaml syntax

### ISSUE THREAD

**Issue by bedge** [awslabs/aws-cfn-template-flip#8]
Rather than the traditional yaml syntax, use the AWS-specific version, ie:
```
!Join [ ":", [ a, b, c ] ]
```
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-join.html

**Comment by stilvoid** [comment]
I'm not sure I understand the request here.

See the following:
```
$ echo '{"Fn::Join":[":", ["a","b","c"]]}' | cfn-flip
!Join [':', [a, b, c]]
```

**Comment by bedge** [comment]
This request was filed before the new yaml-specific syntax was added, closing.
thanks.
