### ISSUE TITLE
Python 2.7 support for latest release

### ISSUE THREAD

**Issue by mervynrussell** [awslabs/aws-cfn-template-flip#81]
Just noticed that there is no 2.7 compatible package in PyPI for the 1.2.1 release.   Has support for 2.7 been dropped?

**Comment by stilvoid** [comment]
Thanks for raising this! That is absolutely not intentional so let me see what went wrong with the PyPi update and I'll fix it shortly.

**Comment by stilvoid** [comment]
Well, I'm not sure how it got missed out the first time but there's a source release there now which will work for python2 :)

**Comment by mervynrussell** [comment]
Thanks Steve, much appreciated :)
