### ISSUE TITLE
PyYaml conflict

### ISSUE THREAD

**Issue by gimlidc** [awslabs/aws-cfn-template-flip#86]
The requirement for PyYaml 3.1.1 causes fatal conflict with awscli and aws-sam-cli. This dependency should be upgraded to 5.1.1

**Comment by koiker** [comment]
The current configuration of `setup.py`has PyYaml 4.1 or higher.

```
install_requires=[
        "Click",
        "PyYAML>=4.1",
        "six",
    ],
``` 

It's supposed to work with other packages that has requirements of higher version.

**Comment by ctd** [comment]
Hi @gimlidc,

I'm not able to reproduce this problem. Could you provide some more information about the version of cfn-flip you're using, and what steps you to took to encounter this error?

**Comment by ctd** [comment]
Closing: unable to reproduce. 

Please comment and reopen if you have further information to support reproducing this issue.
