### ISSUE TITLE
ODict not working properly after deep copied

### ISSUE THREAD

**Issue by bachew** [awslabs/aws-cfn-template-flip#89]
I created a [pull request](https://github.com/awslabs/aws-cfn-template-flip/pull/88) for this bug, basically the following test failed before the fix:

```python
def test_post_deepcopy_repr():
    dct = ODict([("a", 1)])
    dct2 = deepcopy(dct)
    assert repr(dct) == repr(dct2)
    dct2["b"] = 2
    assert repr(dct) != repr(dct2)
```

**Comment by koiker** [comment]
Thanks for your PR!

I've merged your changes and as soon as @stilvoid  review them he will publish the new version of the package.
