### ISSUE TITLE
Improve conversion output for multiline strings

### ISSUE THREAD

**Issue by dragonfly-net** [awslabs/aws-cfn-template-flip#90]
I have some code in yaml
```
        UserData:
          Fn::Base64: !Sub |
            write_files:
              - path: /etc/yum.repos.d/nix.repo
                content: |
                   [nix]
                   name=nix Repository
....
```

But after converting to json (corporate standart) i've got something terrible
```
               "UserData": {
                    "Fn::Base64": {
                        "Fn::Sub": "write_files:\n  - path: /etc/yum.repos.d/nix.repo\n    content: |\n       [nix]\n       name=nix Repository\n.....
```
I think - need replace Sub to Find and var names inside to {"Sub":"var"}
Or at least multiline strings, not 1 string

**Comment by stilvoid** [comment]
The main problem here is that JSON does not support nicely-formatted multi-line strings which is one of yaml's major advantages when it comes to CloudFormation.

You could consider keeping the contents in a separate file and using a template engine to compile the final template as needed if you absolutely must stick with JSON.

There's no way to fix JSON's lack of support for formatted strings within cfn-flip :(

**Comment by stilvoid** [comment]
Closing for now. Please re-open if you think there's something we can improve in cfn-flip :)
