### ISSUE TITLE
Travis builds for Python 3.6 and 3.7 are failing

### ISSUE THREAD

**Issue by ctd** [awslabs/aws-cfn-template-flip#96]
See:
 * https://www.travis-ci.org/github/awslabs/aws-cfn-template-flip/jobs/676095898
 * https://www.travis-ci.org/github/awslabs/aws-cfn-template-flip/jobs/676095899

Python 2.7 builds are not failing (although those should probably be removed anyhow).

**Comment by koiker** [comment]
As I suspected there had some bug in the building process and they failed; I just ran again the build and now all python versions passed.
