### ISSUE TITLE
Feature: add flag for dry run

### ISSUE THREAD

**Issue by andres-lowrie** [awslabs/aws-cfn-template-flip#99]
Would be super helpful it there was a flag that just showed the changes that would occur without actually performing them. 

This could be helpful in CI/CD pipelines as a check.

**Comment by koiker** [comment]
Hi Andres,

Normally we use cfn-flip to change from json to yaml and vice-versa and this produce completely different document format.

But just in case of a yaml to yaml conversion that you could get some opinionated cleanup you can get the changes running this command for example:

```
cfn-flip -i yaml -y -c ./examples/test_yaml_def_string_with_sub.yaml | diff ./examples/test_yaml_def_string_with_sub.yaml -
```

**Comment by andres-lowrie** [comment]
ty very much! Have a great weekend!
